name       : qtpass
version    : 1.3.2
release    : 17
source     :
    - https://github.com/IJHack/QtPass/archive/v1.3.2.tar.gz : 7a68e1afe68462c878c212a79c40ade5ba14b72710c5e62450cf54c7b5621254
license    : GPL-3.0-or-later
component  : security
summary    : QtPass is a multi-platform GUI for pass, the standard unix password manager.
description: |
    QtPass is a multi-platform GUI for pass, the standard unix password manager.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(xkbcommon)
rundeps    :
    - password-store
setup      : |
    %qmake PREFIX=$installdir/usr
build      : |
    lrelease localization/localization_*
    %make
install    : |
    %make_install
    install -Dm00644 qtpass.desktop $installdir/usr/share/applications/qtpass.desktop
    install -Dm00644 artwork/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/qtpass-icon.svg
