name       : qtpass
version    : 1.2.1
release    : 15
source     :
    - https://github.com/IJHack/qtpass/archive/v1.2.1.tar.gz : f2aa1a54ed273546aab8933e560218b7b59f7f07000d93c018ec8d6ccdedcd5d
license    : GPL-3.0-or-later
component  : security
summary    : QtPass is a multi-platform GUI for pass, the standard unix password manager.
description: |
    QtPass is a multi-platform GUI for pass, the standard unix password manager.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5Help)
    - pkgconfig(xkbcommon)
rundeps    :
    - password-store
setup      : |
    sed -i 's:\$\$\[QT_INSTALL_TESTS]:${installdir}:g' tests/tests.pri
    %qmake PREFIX=$installdir/usr
build      : |
    lrelease localization/localization_*
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/share/icons
    install -Dm644 artwork/icon.png $installdir/usr/share/pixmaps/qtpass-icon.png
    cp $installdir/usr/share/pixmaps/qtpass-icon.png $installdir/usr/share/icons/
    install -Dm644 qtpass.desktop $installdir/usr/share/applications/qtpass.desktop
