name       : qtpass
version    : 1.0.2
release    : 2
source     :
    - https://github.com/IJHack/qtpass/archive/v1.0.2.zip : 36b8b0dd6b16d34c26a5d7bd9056143493813a48ce8fb354ba54b629925f2e55
license    : GPL-3.0
summary    : QtPass is a multi-platform GUI for pass, the standard unix password manager.
description: |
    QtPass is a multi-platform GUI for pass, the standard unix password manager.
builddeps  :
    - pkgconfig(egl)
    - pkgconfig(Qt5OpenGL)
    - pkgconfig(xkbcommon)
rundeps:
    - password-store
setup      : |
    qmake .
build      : |
    %make
install    : |
    %make_install
    mkdir -p $installdir/usr/share/icons
    install -Dm755 qtpass $installdir/usr/bin/qtpass
    install -Dm644 artwork/icon.png $installdir/usr/share/pixmaps/qtpass-icon.png
    cp $installdir/usr/share/pixmaps/qtpass-icon.png $installdir/usr/share/icons/
    install -Dm644 qtpass.desktop $installdir/usr/share/applications/qtpass.desktop
